FROM ubuntu
MAINTAINER "Mattias Hemmingsson" <matte.hemmingsson@gmail.com>
RUN apt-get update && apt-get install python-pip -y
RUN apt-get update && sudo apt-get install build-essential autoconf libtool pkg-config python-opengl python-imaging python-pyrex python-pyside.qtopengl idle-python2.7 qt4-dev-tools qt4-designer libqtgui4 libqtcore4 libqt4-xml libqt4-test libqt4-script libqt4-network libqt4-dbus python-qt4 python-qt4-gl libgle3 python-dev -y
RUN apt-get update &&  apt-get install libpq-dev python-dev libxml2-dev libxslt1-dev libldap2-dev libsasl2-dev libffi-dev -y
RUN pip install flask-ask python-jenkins


WORKDIR /code
CMD python app.py
